[helpers]

[default]
depends = []

[default.files]
"git/config" = "~/.gitconfig"
"git/global-ignore" = "~/.gitignore_global"
"vim/.vimrc" = "~/.vimrc"
".ideavimrc" = "~/.ideavimrc"
"powershell" = "~/.powershell"
"bash/bashrc" = "~/.bashrc"
"zsh/rc" = "~/.zshrc"
"zsh/env" = "~/.zshenv"
"nvim-config" = "~/.config/nvim"
"tmux.conf" = "~/.tmux.conf"
"gitui" = "~/.config/gitui"
# discord with flatpak -- probably should be factored to a project
"discord/settings.json" = { target = "~/.var/app/com.discordapp.Discord/config/discord/settings.json", type = "template" }
"fselect/config.toml" = "~/.config/fselect/config.toml"
"broot" = "~/.config/broot/config.hjson"
"github-cli/config.yml" = "~/.config/gh/config.yaml"
"glow" = "~/.config/glow"
"kitty" = { target = "~/.config/kitty", type = "symbolic" }
"alacritty" = { target = "~/.config/alacritty", type = "symbolic" }
"ipython/ipython_config.py" = "~/.ipython/profile_default/ipython_config.py"
"nix" = "~/.config/nix"
"atuin" = "~/.config/atuin"
"zellij" = "~/.config/zellij"

[default.variables]
git_name = "ditsuke"
git_email = "ditsuke@protonmail.com"
gpg_key_id = "8fd2153f4889541a54f1e09e71b6c31c8a5a9d21"
gpg_binary = "/usr/bin/gpg"

[fedora-gnome]
depends = []

[fedora-gnome.files]
"dconf/settings.ini" = "~/.config/dconf/settings.ini"

[pop-shell]
depends = []

[pop-shell.files]
"pop-shell" = "~/.config/pop-shell"
