[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
"vim/.vimrc" = "~/.vimrc"
".ideavimrc" = "~/.ideavimrc"
"powershell" = "~/.powershell"
"nvim" = "~/AppData/local/nvim"

[windows]
depends = []

[windows.files]
"windows-terminal" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
# not portable yet
"bash/.bash_profile" = "~/.bash_profile"
"bash/.bashrc" = "~/.bashrc"

[default.variables]
