[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
"vim/.vimrc" = "~/.vimrc"
".ideavimrc" = "~/.ideavimrc"
"powershell" = "~/.powershell"
"nvim" = "~/.config/nvim"

[default.variables]
gpgbinary = "/usr/bin/gpg"
