[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
"vim/.vimrc" = "~/.vimrc"
".ideavimrc" = "~/.ideavimrc"
"powershell" = "~/.powershell"
"nvim" = "~/.config/nvim"

[default.variables]
git_name = "ditsuke"
git_email = "ditsuke@protonmail.com"
gpg_key_id = "8fd2153f4889541a54f1e09e71b6c31c8a5a9d21"
gpg_binary = "/usr/bin/gpg"

