[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
".vimrc" = "~/.vimrc"
".bash_profile" = "~/.bash_profile"
".bashrc" = "~/.bashrc"
".ideavimrc" = "~/.ideavimrc"
"powershell" = "~/.powershell"
"nvim" = "~/AppData/local/nvim"
"windows-terminal" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"

[default.variables]

