[services.files]
"gram/fix-gram.service" = { target = "/etc/systemd/system/fix-gram.service", type = "template", owner = "root" }
"gram/fix-gram.sh" = { target = "/usr/local/bin/fix-gram.sh", type = "template", owner = "root" }
