[server-services]
depends = []

[server-services.files]
"services/taskchampion-server.service" = { target = "/etc/systemd/system/taskchampion-server.service", type = "template", owner = "root" }

[server-services.variables]
username = "ditsuke"
taskserver-port = "50851"

[lg-gram]
depends = []

[lg-gram.files]
"gram/fix-gram.service" = { target = "/etc/systemd/system/fix-gram.service", type = "template", owner = "root" }
"gram/lg-gram-fixes.sh" = { target = "/usr/local/bin/lg-gram-fixes.sh", type = "template", owner = "root" }
