[default]
depends = []

[default.files]
# widows only
"windows-terminal" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
# not portable yet
"bash/.bash_profile" = "~/.bash_profile"
"bash/.bashrc" = "~/.bashrc"
# overrides
"nvim" = "~/AppData/local/nvim"
